apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-solver-deployment
  template:
    metadata:
      labels:
        app: multi-solver-deployment
    spec:
      containers:
      - name: solver
        image: sudoku-solver:0.6
        ports:
        - containerPort: 1632
          name: solver-port
---
apiVersion: v1
kind: Service
metadata:
  name: multi-solver-service
spec:
  selector:
    app: multi-solver-deployment
  ports:
    - protocol: TCP
      port: 1632
      targetPort: 1632
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: solver-server:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3264
      targetPort: 3264
  type: LoadBalancer
